version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    #    environment:
    #      DB_URI: "${ATLAS_URI}"
    #      PORT: "${PORT}"
    #      JWT_SECRETKEY: "${JWT_SECRETKEY}"
    #    depends_on:
    #      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

#  mongo:
#    image: mongo:4.4
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db
#    healthcheck:
#      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#    networks:
#      - app-network
#
#volumes:
#  mongo_data:

networks:
  app-network:
    driver: bridge
